### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by theofidry** [bamarni/composer-bin-plugin#12]
After playing with it for a couple of month, I realise that installing some binaries to avoid any dependency conflict is, indeed a use case, but it is much more interesting to use to install optional dependencies. For example if I have a library `acme/lib`, I may have frameworks bridges in it, in which case it is interesting to install them in sub-directories via this plugin to avoid any conflict between those dependencies and be able to install in parallel both Symfony and Laravel, and be able to run the tests for my lib, the Laravel and Symfony bridge at once.

There is certainly some subtleties when doing that, https://github.com/wikimedia/composer-merge-plugin that you pointed me at one point does help to solve them and I'm working to simplify a bit the set up.

So this other use case made me realise that linking the binaries is indeed a nice feature (and was the original goal of this plugin?), but ultimately the other usage is as interesting, requires no change in this plugin and describe more what this plugin is really about: managing sub-packages. So maybe another name would be more suited for this plugin? `composer-subpackages-plugin`?

**Comment by bamarni** [comment]
When creating it I chose to name it like this because with the binary links it's not just a subpackage plugin. The original focus is indeed to deal with binaries, the namespace thing is just an implementation detail and might change if there appears to be a better approach to tackle this in the future. That's also why I've started with 0.* releases and kept the name generic, not even `composer-bin-namespaces-plugin` or similar.

I'd like to keep the project easily understandable for new comers so focusing on the bin thing, even though as we discussed I could see how it can help for other use cases but that was kind of unfortunate :)
