### ISSUE TITLE
Is the namespace parameter necessary?

### ISSUE THREAD

**Issue by uberhacker** [bamarni/composer-bin-plugin#29]
What is wrong with just using `org/project` as the namespace?  This would simplify the command to be just `composer bin require org/project` and could create the `vendor-bin/org/project` directory.  This way could also allow multiple projects to reside in the same `vendor-bin/org` namespace.

**Comment by bamarni** [comment]
The approach of this plugin is just to proxy commands to a namespace, to do what you suggest it'd need to do extra parsing, I also think it could be confusing as there'd be 2 different syntaxes.

I didn't get the other part, it should already be possible to have multiple packages in the same namespace, eg.  `composer bin org require org/project org/project2`

**Comment by Taluu** [comment]
Instead of the namespace parameter, we could also add a "map" config in the composer.json ;

```json
{
    "bin-bamarni": {
         "namespaces": {
            "foo": ['package 1', 'package 2'],
            "bar": ['package 3']
         }
    }
}
````

Of course, the namespace arg part could still be supported.

**Comment by bamarni** [comment]
@Taluu : see #28

**Comment by Taluu** [comment]
This is not quite the same actually. What I'm proposing here is *not* declaring dependencies and what not in the main composer json file. What I'm suggesting here is declaring the _namespaces_ in the main composer file. For the root dependencies inside the root composer json file.

**Comment by bamarni** [comment]
I see, what would this solve though, is there anything which is not supported currently that this would enable?

**Comment by Taluu** [comment]
So that a simple `composer bin install` would then base itself on the config, without having to (potentially) forget the namespace, and install everything in one go.

The use-case that I have is actually to have a composer.json committed file on my dotFiles repo (I already have one) and just do a `composer global bin install`, without having to remember each namespaces and so on. Without having to do X commands for X namespaces.

**Comment by theofidry** [comment]
@Taluu can't you already do that by adding a `composer bin all install` as a post-install hook?

**Comment by Taluu** [comment]
On a new install, it won't be in the right namespace.

**Comment by theofidry** [comment]
What do you mean?

**Comment by Taluu** [comment]
On a another machine, I may need to sync my dotfiles, which includes a global `composer.json` (userland), with a set of dependencies ; currently, I will need to do a `composer global bin foo require package 1 package 2`, then a `composer global bin bar require package 3`, ... and so on.

I would like to be able to set the namespaces "definitely" in my composer file (see my suggestion) through a config of some sort so that I can actually just do a `composer bin all install` and that's it. 

Even better I think, with this system, instead of having to make a `bin install`, just do an `install` which checks if there are namespaces (so that not *all* packages are namespaced... plugins for example), so that a simple `composer install` (composer installs plugins first and then activate them...) does the trick

**Comment by theofidry** [comment]
But you can keep track of those namespaced `composer.json` still. For example:

```
~/.composer
    composer.json
    composer.lock
    vendor-bin/*/
        composer.json
        composer.lock
```

So if you keep them in sync with your dotfiles and have the hook, a simple `composer global install` will do all the work.

>I would like to be able to set the namespaces "definitely" in my composer file (see my suggestion) through a config of some sort so that I can actually just do a composer bin all install and that's it.

If I understand correctly at the end of day you want to be able to declare another `composer.json` content from your main `composer.json`.

Whilst that could be done, I'm not sure that it's worth: it requires significant refactoring and you'll have to do something along the lines of

- go to the new created directory (we already do that)
- dump the content with your dep in a `composer.json` (right now we don't need to do that as the `composer.json` already exists)
- run composer
- remove the `composer.json` (otherwise you would introduce the issue of keeping that dumped `composer.json` with what you declare in the main `composer.json`)

It adds significant complexity for not much IMO

**Comment by Taluu** [comment]
> So if you keep them in sync with your dotfiles and have the hook

And *that's* the problem right there. I don't want to sync N composer.json files, I just want to sync *one* and be done with it.

And once it is installed (For the first time...), I don't really care for the sub created files. If the need ever arise that I need to change something (changing the version, removing the dep, ...), I can then deal with that separately. With such a config, and probably some inheritance, it's not really a problem anymore...

**Comment by theofidry** [comment]
> I don't want to sync N composer.json files, I just want to sync one and be done with it.

That's another story :) But as I said, IMO that use case don't really justify the added complexity (at least not enough for me to work on it) especially since it's a use case that arise only for global dependencies, which for me is _very_ limited.

IMO the true worth of that plugin is for project's `composer.json` where it allows to track tools like phpstan in your project without messing up with your project dependencies or more complex mono-repo configuration like done in https://github.com/nelmio/alice coupled with https://github.com/theofidry/composer-inheritance-plugin.

Kill global composer.json :P

**Comment by sepehr** [comment]
> And that's the problem right there. I don't want to sync N composer.json files, I just want to sync one and be done with it. — [**@Taluu**](https://github.com/Taluu) on [Sep 10, 2017, 3:26 PM GMT+4:30](https://github.com/bamarni/composer-bin-plugin/issues/29#issuecomment-328335106 "2017-09-10T10:56:55Z")_

I just [migrated](https://github.com/sepehr/dotfiles/commit/0696f1a63343eeb5fd6ad8ae273ea2a9e2edc25f) from cgr to bin plugin and I absolutely feel for you as I collect/sync my global packages in my dotfiles. But I agree with @theofidry that our usecase alone, doesn't justify the added complexity to the plugin.  

I think we can live with an extra directory in our dotfiles.
