### ISSUE TITLE
Additional commands to list and remove bin containers.

### ISSUE THREAD

**Issue by derhasi** [bamarni/composer-bin-plugin#35]
@bamarni thanks for that great composer plugin. I'm using it for a while now. It saved me from a lot of headaches.

But when working with the command, in some cases I missed some functionality. Therefore I'd propose to add two new commands:

## bin:list
Provides an overview of "installed" bin directories/containers/scopes (or how you would name it). Maybe an additional option `--with-require` could also list the root dependencies of that scope.

## bin:remove {scope}
Will remove the directory for `{scope}` and remove all bin symlinks for that scope.

**Comment by theofidry** [comment]
While I understand those two commands can help, they have very natural existing ones already:

```
# bin:list
ls -l vendor-bin

# bin:remove {scope}
rm -r {scope}
```

I'm not sure it's worth to try to abstract this and write it in PHP when they are easy one liners bash commands

**Comment by hawkeyetwolf** [comment]
The only difference is that just deleting the bin directory doesn't also clean up any symlinks in the "all" bin.

**Comment by theofidry** [comment]
After checking this again, having a list command would be trivial but a remove one a lot more complex. Indeed this involves:

- listing all the namespaces (easy)
- for each namespace, list all the dependencies
- for each dependency execute a `composer remove`

I suspect it will be quite slow and annoying and no one would use it due to its slowness besides not being trivial to implement.

If someone is willing to implement it I'll be happy to consider it, but otherwise I don't really wish to work on this.
