### ISSUE TITLE
[Question] Allow to install bin not from a composer package?

### ISSUE THREAD

**Issue by seyfer** [bamarni/composer-bin-plugin#37]
For example, we want to use some bin in our project, like scss made with Ruby or https://github.com/phrase/phraseapp-client/releases/download/1.6.0/phraseapp_linux_amd64 made with Go. And these bins obviously are not composer packages and we want to include just compiled bin.

Could it be achieved with a composer or with this plugin? Or support could be added?

**Comment by theofidry** [comment]
I don't think this belongs to this plugin: this plugin is only about interacting with different `composer.json` packages: `composer bin <namespace> smth` will execute the command `composer smth` in the directory `vendor-bin/<namespace>`. That's it.

So IMO your binaries should be added directly to your project, or if you feel bad about it because binaries are heavy, you can add a way to download/create them from a bash file, Makefile for example.
