### ISSUE TITLE
Conflicting namespace

### ISSUE THREAD

**Issue by theofidry** [bamarni/composer-bin-plugin#5]
Scenario: you have a package `symfony/yaml` in your `package.json`, which will be resolved in the version `3.1.2`. Now you have `phpunit/phpunit` installed in a `phpunit` namespace. To that point everything works fine. Somehow, you must use `random/phpunit-plugin` with your phpunit which requires `symfony/yaml` as well. In the `phpunit` namespace, this `symfony/yaml` is resolved in the version `2.8.3`. Now let's assume `random/phpunit-plugin` cannot work with `symfony/yaml 3.1.2` and your project cannot work with the `2.8.3` version. 

What will happen? You will you get an error somewhere or will it silently fail or result in some weird bugs?

**Comment by bamarni** [comment]
The plugin wouldn't raise an error, you might experience strange things when running phpunit, but it might as well not cause any issue.

I think it is more appropriate to wait for a dependency conflict before using this plugin, rather than using this plugin in advance in order to avoid dependency conflicts. Because a dependency conflict can be addressed in numerous ways depending on the issue, eg. by loosening a constraint in composer.json, submitting a patch to the upstream project, and using this plugin should only be a last resort solution imo, after the situation has been analyzed.

That being said, in practice it is usually fine, there are multiple kinds of cli tools and only the ones which are executing your php code in the same process are potentially concerned. I'd tend to believe that tools like phpunit belong more to the require-dev section. The problem you're describing exists for a long time btw. What if any of phpunit/phpunit dependencies were in conflict with your project's dependencies, and you're running your test suite through a phpunit phar? Yet people have been doing this for years :)

**Comment by theofidry** [comment]
My concern is not so much that this plugin doesn't solve this conflict problem, but can lead to very *sly* errors by silent failing or giving weird outputs. I find this rather dangerous.

>What if any of phpunit/phpunit dependencies were in conflict with your project's dependencies, and you're running your test suite through a phpunit phar

Yeah I learned the hard way that tools that *run* your code, as opposed to static analysis tools, *should* be installed as a dev dependency.

I gave the use case of PHPUnit but I don't think it's the best one. Let me give you another scenario: I'm developing a library. This library has bridges to different frameworks, e.g. Symfony and Laravel. What this plugin can allow me to do is:

- have my root `package.json` without any framework related thingy
- have a `symfony` and `laravel` namespace where I can respectively require `symfony/symfony` and `laravel/laravel` and things required for the Symfony bridge or Laravel bridge

So that way I can run my tests without any framework related thing, then running them with the Symfony bridge and lastly the ones with the Laravel bridge. This is now possible even though you might not be able to install Symfony and Laravel at the same time because it would create conflicts.

**Comment by bamarni** [comment]
Your last scenario seems out of the scope of this plugin unfortunately, which original purpose was to deal with bin dependencies.

It is a rather uncommon setup to keep all the code on the library src and have different vendor / autoloads for each bridge. If for some reason you want to extract laravel and symfony dependencies from your library's composer.json, why not turning those bridges into standalone packages?

> Maybe the only thing that would be needed is somehow include the dep from package.json to the the in the symfony and laravel namespace, is there a neat way to do that?

I don't see a simple way to do that at the moment, there is a pending PR somewhere on composer/composer to allow composer.json inheritance, might help for this kind of use cases. However I find it somehow wasteful as it would duplicate a lot of installed packages. Might be more suited to just run a dry-run update including the main composer.json deps to be sure it's compatible, then only install the ones from the namespace.

**Comment by theofidry** [comment]
>If for some reason you want to extract laravel and symfony dependencies from your library's composer.json, why not turning those bridges into standalone packages?

It's way easier to manage. By bridge it's almost only registering the services to the framework DIC. Anything more specific to the framework is out of scope and should be done in a dedicated library. But putting it in a standalone library makes it horribly hard to maintain.

I guess the last use case should be deal with by adding the library itself manually as a dep...

Ok thanks very much your answers, it helped to re-assess a few things. I'm still unhappy with the potential versions mismatch errors, but it's up to you to consider if it should be in the plugin scope or not.

**Comment by bamarni** [comment]
You're welcome, you brought interesting concerns.

Just an idea, maybe [this plugin](https://github.com/wikimedia/composer-merge-plugin) could somehow fix your issue (being required inside your namespaces composer.json and extending the main one)?

**Comment by theofidry** [comment]
Hm interesting. It could do the job although to be honest I just had to add the library itself on dev-master so not a big deal :)
