### ISSUE TITLE
Doesn't work with ergebnis/composer-normalize

### ISSUE THREAD

**Issue by Jamesking56** [bamarni/composer-bin-plugin#68]
This bin package doesn't seem to work with https://github.com/ergebnis/composer-normalize, I believe this is because it registers as a Composer plugin rather than an actual binary file.

**Comment by theofidry** [comment]
What exactly do you mean by "doesn't work"?

**Comment by Jamesking56** [comment]
`composer normalize` is command not found when install as a vendor-bin package. So it doesn't function at all

**Comment by theofidry** [comment]
how is the `ergebnis/composer-normalize` installed though? Because if you don't install it as a general plugin (i.e. your user composer.json), it's only available for a specific `composer.json`. This means if you install it in your root `composer.json` it won't work for the `vendor-bin/foo/composer.json` (unless you install it there too)

**Comment by theofidry** [comment]
`composer normalize` would definitely not work with the previous install command as it will install the package to `vendor-bin/normalize/ergebnis/composer-normalize`. The command should `composer bin normalize normalize`.

That said I never tried it with a plugin that executes a command this way so I don't know if it will work

**Comment by theofidry** [comment]
Fixed by #115
